Controllers/UtilsController.cs
using Audium.Models.DbContexts;
using Audium.Models.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Audium.Controllers
{
    public class UtilsController : Controller
    {
        private readonly UserManager<AudiumUser> _userManager;

        public UtilsController(MusicDbContext musicDb, UserManager<AudiumUser> userManager)
        {
            _userManager = userManager;
        }

        [HttpPost]
        public async Task<IActionResult> ToggleDarkMode()
        {
            var user = await _userManager.GetUserAsync(User);

            user.DarkMode = !user.DarkMode;

            await _userManager.UpdateAsync(user);

            return Ok();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Audium - @ViewData["Title"]</title>
    <link rel="icon" type="image/png" href="~/img/favicon.png" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700,500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:500&display=swap" rel="stylesheet">
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet">
    @RenderSection("Stylesheets", required: false)
    <script src="~/lib/jquery.min.js"></script>
</head>
<body>
    @RenderBody()

    <script>
        $(".sidebar .checkbox-input").change(function () {
            console.log("change");
            $.ajax({
                url: "@Url.Action("ToggleDarkMode", "Utils")",
                type: "POST",
                success: function () {
                    if ($(".main-container").hasClass("dark")) {
                        $(".main-container").removeClass("dark");
                    }
                    else {
                        $(".main-container").addClass("dark");
                    }
                }
            })
        })
    </script>
</body>
</html>

Views/Shared/_Navbar.cshtml
<div class="sidebar">
    <a class="logo" href="@Url.Action("Index", "Home")"></a>

    <ul class="sidebar-links">
        <li class=@(ViewData["Page"] == "Home" ? "active" : "")><a href="@Url.Action("Index", "Home")"><i class="fas fa-home"></i> Home</a></li>
        <li class=@(ViewData["Page"] == "New Playlist" ? "active" : "")><a href="@Url.Action("New", "Playlist")"><i class="fas fa-plus"></i> New Playlist</a></li>
    </ul>

    <div class="checkbox-input">
        <input type="checkbox" id="toggleDarkTheme" name="toggleDarkTheme" @(ViewBag.darkMode ? "checked" : "") />
        <label for="toggleDarkTheme">Dark Mode</label>
    </div>

    <form class="logout-button" id="logout" action="@Url.Action("Logout", "Auth")" method="post">
        <input class="button button-sm fancy-button" type="submit" value="Logout" />
    </form>
</div>